# Generated by Django 4.0.4 on 2022-04-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='passwords',
            new_name='password',
        ),
    ]
